# Host bring-up only. Supply USE_LLVM and compiler paths explicitly at configure time.
set(CMAKE_BUILD_TYPE Release CACHE STRING "Build configuration" FORCE)
set(USE_HOST_ONLY_AUTO_COPY_GUARD ON CACHE BOOL "Reject unavailable auto-copy lowering in the restricted checkout" FORCE)
set(USE_CUDA OFF CACHE BOOL "CUDA disabled" FORCE)
set(USE_ROCM OFF CACHE BOOL "ROCm disabled" FORCE)
set(USE_OPENCL OFF CACHE BOOL "OpenCL disabled" FORCE)
set(USE_VULKAN OFF CACHE BOOL "Vulkan disabled" FORCE)
set(USE_METAL OFF CACHE BOOL "Metal disabled" FORCE)
set(USE_CUTLASS OFF CACHE BOOL "CUTLASS disabled" FORCE)
set(USE_MLIR OFF CACHE BOOL "MLIR disabled" FORCE)
set(USE_RPC OFF CACHE BOOL "Remote execution deferred" FORCE)
set(USE_GTEST OFF CACHE STRING "No external GTest dependency" FORCE)
set(USE_LIBBACKTRACE OFF CACHE STRING "No external libbacktrace dependency" FORCE)
set(USE_BLAS none CACHE STRING "Use TVM-generated host kernels" FORCE)
set(USE_CCACHE OFF CACHE STRING "Keep the build independent of shared compiler caches" FORCE)
set(USE_ALTERNATIVE_LINKER OFF CACHE STRING "Use the selected compiler's default linker" FORCE)
set(HIDE_PRIVATE_SYMBOLS ON CACHE BOOL "Limit exported symbols" FORCE)
